# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1amTFSlhJUfNktMnG5u5EWkRo2_Z2Ir
"""

# app.py
import streamlit as st
from qa_engine import PDF_QA

st.set_page_config(page_title="📄 PDF Q/A Chatbot")

st.title("📘 Ask Questions from the Black Friday PDF")
st.write("📄 Using: *Nonfiction Reading Test Black Friday.pdf*")

# Initialize backend (loads hardcoded PDF from backend)
qa = PDF_QA()

# Take question input from user
question = st.text_input("❓ Enter your question:")

if st.button("Get Answer") and question:
    with st.spinner("🔎 Thinking..."):
        answer = qa.ask(question)
        st.success(f"🤖 Answer: {answer}")