# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1amTFSlhJUfNktMnG5u5EWkRo2_Z2Ir
"""

import streamlit as st
import backend
st.set_page_config(page_title="📘 PDF Q&A", layout="centered")
st.title("📘 Ask Questions from PDF")
st.markdown("PDF Used: *Nonfiction Reading Test Black Friday.pdf*")
query = st.text_input("Enter your question:")
if query:
    with st.spinner("Finding answer..."):
        answer = answer_question(query)
    st.success(f"**Answer:** {answer}")
